// ============================================================
//  ✏️  EDITE AQUI para adicionar, remover ou atualizar casas
// ============================================================
import type { BettingHouse } from './types';

export const houses: BettingHouse[] = [
  {
    id: 'lotogreen',
    name: 'LotoGreen',
    url: 'https://lotogreen.bet.br/',
    emoji: '🍀',
    color: '#00e676',
    rating: 4,
    category: ['esportes', 'cassino'],
    bonus: { label: 'Bônus de Boas-Vindas', detail: 'Bônus no primeiro depósito' },
    tags: ['depósito fácil', 'suporte rápido'],
  },
  {
    id: 'lottu',
    name: 'Lottu',
    url: 'https://www.lottu.bet.br/',
    emoji: '🎰',
    color: '#7c3aed',
    rating: 3,
    category: ['esportes', 'cassino'],
    bonus: { label: 'Cashback Semanal', detail: 'Cashback toda semana' },
    tags: ['cashback', 'slots'],
  },
  {
    id: 'novibet',
    name: 'Novibet',
    url: 'https://www.novibet.bet.br/apostas-ao-vivo',
    emoji: '⚡',
    color: '#3b82f6',
    rating: 4,
    category: ['ao-vivo', 'esportes'],
    bonus: { label: 'Odds Melhoradas', detail: 'Odds especiais ao vivo' },
    tags: ['ao vivo', 'odds altas'],
    featured: true,
  },
  {
    id: 'br4',
    name: 'BR4',
    url: 'https://br4.bet.br/',
    emoji: '🇧🇷',
    color: '#22c55e',
    rating: 3,
    category: ['esportes', 'cassino'],
    bonus: { label: 'Bônus BR', detail: 'Promoções exclusivas para brasileiros' },
    tags: ['brasileiro', 'pix'],
  },
  {
    id: 'superbet',
    name: 'Superbet',
    url: 'https://superbet.bet.br/',
    emoji: '🦸',
    color: '#ef4444',
    rating: 4,
    category: ['esportes', 'ao-vivo'],
    bonus: { label: 'Super Bônus', detail: 'Bônus + free bets' },
    tags: ['free bets', 'futebol'],
    featured: true,
  },
  {
    id: 'donald',
    name: 'Donald Bet',
    url: 'https://donald.bet.br/',
    emoji: '🦆',
    color: '#f59e0b',
    rating: 3,
    category: ['cassino', 'esportes'],
    bonus: { label: 'Bônus Pato', detail: 'Bônus no cadastro' },
    tags: ['cassino', 'slots'],
  },
  {
    id: 'ginga',
    name: 'Ginga',
    url: 'https://ginga.bet.br/',
    emoji: '🎭',
    color: '#06b6d4',
    rating: 4,
    category: ['esportes', 'cassino'],
    bonus: { label: 'Bônus Ginga', detail: 'Bônus progressivo' },
    tags: ['progressivo', 'futebol'],
    note: 'Boa interface, gosto bastante',
  },
  {
    id: 'betano',
    name: 'Betano',
    url: 'https://betano.bet.br/',
    emoji: '🏆',
    color: '#ffd600',
    rating: 5,
    category: ['esportes', 'ao-vivo', 'cassino'],
    bonus: { label: 'Bônus Líder', detail: 'Melhor bônus de boas-vindas do mercado' },
    tags: ['top tier', 'ao vivo', 'pix'],
    featured: true,
    note: 'Minha preferida — odds excelentes',
  },
  {
    id: 'vaidebet',
    name: 'VaideBet',
    url: 'https://vaidebet.bet.br/',
    emoji: '🚀',
    color: '#8b5cf6',
    rating: 4,
    category: ['esportes', 'cassino'],
    bonus: { label: 'Vai de Bônus', detail: 'Bônus + rodadas grátis' },
    tags: ['rodadas grátis', 'esportes'],
  },
  {
    id: 'hiper',
    name: 'Hiper Bet',
    url: 'https://hiper.bet.br/ptb/bet/main',
    emoji: '🔥',
    color: '#f97316',
    rating: 3,
    category: ['esportes', 'ao-vivo'],
    bonus: { label: 'Bônus Hiper', detail: 'Promoções diárias' },
    tags: ['diário', 'esportes'],
  },
  {
    id: 'esportesdasorte',
    name: 'Esportes da Sorte',
    url: 'https://esportesdasorte.bet.br/ptb/bet/main',
    emoji: '🎯',
    color: '#10b981',
    rating: 4,
    category: ['esportes', 'ao-vivo'],
    bonus: { label: 'Sorte Grande', detail: 'Bônus de primeiro depósito + odds especiais' },
    tags: ['confiável', 'futebol'],
    featured: true,
  },
  {
    id: 'apostaganha',
    name: 'ApóstaGanha',
    url: 'https://apostaganha.bet.br/cassino?_smartico_dp=dp:gf',
    emoji: '💰',
    color: '#eab308',
    rating: 3,
    category: ['cassino'],
    bonus: { label: 'Ganha Fácil', detail: 'Bônus especial no cassino' },
    tags: ['cassino', 'slots'],
  },
  {
    id: 'voudebet',
    name: 'VoudeBet',
    url: 'https://voudebet.tech/',
    emoji: '✈️',
    color: '#0ea5e9',
    rating: 3,
    category: ['esportes', 'cassino'],
    bonus: { label: 'Vou de Bônus', detail: 'Bônus no registro' },
    tags: ['novo', 'pix'],
  },
  {
    id: 'vixe',
    name: 'Vixe Bet',
    url: 'https://vixe.bet/',
    emoji: '😲',
    color: '#a855f7',
    rating: 3,
    category: ['esportes', 'cassino'],
    bonus: { label: 'Vixe! Bônus', detail: 'Bônus surpresa no cadastro' },
    tags: ['surpresa', 'cassino'],
  },
  {
    id: 'upbet',
    name: 'Up Bet',
    url: 'https://up.bet.br/pt-BR',
    emoji: '⬆️',
    color: '#6366f1',
    rating: 3,
    category: ['esportes', 'cassino'],
    bonus: { label: 'Up Bônus', detail: 'Depósito + bônus automático' },
    tags: ['automático', 'esportes'],
  },
  {
    id: 'mma',
    name: 'MMA Bet',
    url: 'https://mma.bet.br/',
    emoji: '🥊',
    color: '#dc2626',
    rating: 4,
    category: ['esportes', 'ao-vivo'],
    bonus: { label: 'Fight Bonus', detail: 'Bônus especial em lutas ao vivo' },
    tags: ['MMA', 'UFC', 'ao vivo'],
    note: 'Ótimo para apostar em lutas',
  },
  {
    id: 'galera',
    name: 'Galera Bet',
    url: 'https://www.galera.bet.br/cassino',
    emoji: '💩',
    color: '#6b7280',
    rating: 1,
    category: ['cassino'],
    bonus: { label: 'Bônus Ilusório', detail: 'Tem bônus mas as condições são péssimas' },
    tags: ['evitar'],
    isTrash: true,
    note: 'Um lixo — não recomendo',
  },
];

// ============================================================
//  ✏️  CONFIGURAÇÕES GERAIS DO SITE
// ============================================================
export const siteConfig = {
  title: 'BetHub',
  subtitle: 'Minhas Casas de Apostas',
  description: 'Casas onde jogo com bônus disponíveis. Acesse direto pelo link.',
  ownerName: 'Minhas Picks', // nome exibido no header
};
